/*
SQLyog Community v13.2.0 (64 bit)
MySQL - 10.4.25-MariaDB : Database - recipe-rs
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`recipe-rs` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `recipe-rs`;

/*Table structure for table `favorites` */

DROP TABLE IF EXISTS `favorites`;

CREATE TABLE `favorites` (
  `user_id` bigint(20) unsigned NOT NULL,
  `recipe_id` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`user_id`,`recipe_id`),
  KEY `RECIPE_FK` (`recipe_id`),
  CONSTRAINT `RECIPE_FK` FOREIGN KEY (`recipe_id`) REFERENCES `recipe` (`id`),
  CONSTRAINT `USER_FK` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `favorites` */

insert  into `favorites`(`user_id`,`recipe_id`) values 
(36,1),
(36,4),
(36,29),
(39,4),
(39,5),
(39,33),
(41,37),
(43,4),
(43,48);

/*Table structure for table `recipe` */

DROP TABLE IF EXISTS `recipe`;

CREATE TABLE `recipe` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(100) DEFAULT NULL,
  `total-time` varchar(20) DEFAULT NULL,
  `serving-size` varchar(20) DEFAULT NULL,
  `ingr` varchar(1000) DEFAULT NULL,
  `instructions` varchar(5000) DEFAULT NULL,
  `difficulty` varchar(10) DEFAULT NULL,
  `fav` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `TITLE` (`title`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8mb4;

/*Data for the table `recipe` */

insert  into `recipe`(`id`,`title`,`total-time`,`serving-size`,`ingr`,`instructions`,`difficulty`,`fav`) values 
(1,'Jamaican Fried Dumplings','20','6 servings','4 cups all-purpose flour, 2 teaspoons baking powder, 1 1/2 teaspoons salt, 1/2 cup butter, 1/2 cup cold water, 1 cup vegetable oil for frying','In a large bowl, stir together the flour, baking powder and salt. Rub in the butter until it is in pieces no larger than peas. Mix in water 1 tablespoon at a time just until the mixture is wet enough to form into a ball. The dough should be a firm consistency. Knead briefly. Heat the oil in a large heavy skillet over medium heat until hot. Break off pieces of the dough and shape into a patty - kind of like a flat biscuit. Place just enough of the dumplings in the pan so they are not crowded. Fry on each side until golden brown, about 3 minutes per side. Remove from the pan and drain on paper towels before serving.\r\n','easy',1),
(2,'Cuban Ropa Vieja\r\n','255','6 servings','1 tablespoon vegetable oil, 2 pounds beef flank steak, 1 cup beef broth, 1 (8 ounce) can tomato sauce, 1 small onion sliced, 1 green bell pepper seeded and sliced into strips, 2 cloves garlic chopped, 1 (6 ounce) can tomato paste, 1 teaspoon ground cumin, 1 teaspoon chopped fresh cilantro, 1 tablespoon olive oil, 1 tablespoon white vinegar','Heat vegetable oil in a large skillet over medium-high heat. Brown the flank steak on each side, about 4 minutes per side. Transfer beef to a slow cooker. Pour in the beef broth and tomato sauce, then add the onion, bell pepper, garlic, tomato paste, cumin, cilantro, olive oil and vinegar. Stir until well blended. Cover, and cook on High for 4 hours, or on Low for up to 10 hours. When ready to serve, shred meat and serve with tortillas or rice.','hard',0),
(3,'Conch Fritters\r\n','35','8 servings','1 quart oil for frying, 3/4 cup all-purpose flour, 1 egg, 1/2 cup milk, ground cayenne pepper to taste, seasoned salt to taste, salt and pepper to taste, 1 cup chopped conch meat, 1/2 onion chopped, 1/2 green bell pepper chopped, 2 stalks celery chopped, 2 cloves garlic chopped, 2 tablespoons ketchup, 2 tablespoons lime juice, 1 tablespoon mayonnaise, 1 tablespoon hot sauce','Heat the oil in a large pot or deep fryer to 365 degrees F (185 degrees C). In a bowl, mix the flour, egg, and milk. Season with cayenne pepper, seasoned salt, salt, and pepper. Mix in the conch meat, onion, bell pepper, celery, and garlic. Drop the batter by rounded tablespoons into the hot oil, and fry until golden brown. Drain on paper towels. In a bowl, mix the ketchup, lime juice, mayonnaise, hot sauce, salt, and pepper. Serve dipping sauce on the side with the fritters.\r\n','medium',0),
(4,'Easy Mojitos','5','1 cocktail','12 leaves mint, 2 lime slices, 1 teaspoon white sugar or more to taste, 1/4 cup ice cubes or as needed, 1 (1.5 fluid ounce) jigger rum (such as Bacardi), 4 1/2 ounces diet lemon-lime soda (such as Diet Sprite)','Place mint leaves, lime slice, and sugar in bottom of a glass and muddle with a spoon until mint is crushed. Fill glass with ice cubes. Pour rum and soda over the ice stir.\r\n','easy',3),
(5,'Mojo Grilling Marinade','15','3 cups','6 cloves garlic coarsely chopped, 1/2 cup minced yellow onion, 1 cup freshly squeezed orange juice, 1/2 cup freshly squeezed lime juice, 1/2 teaspoon ground cumin, 1 teaspoon dried oregano flakes, 1/2 teaspoon lemon-pepper seasoning, 1/2 teaspoon freshly ground black pepper, 1 teaspoon kosher salt, 1/4 cup chopped cilantro, 1 teaspoon hot pepper sauce (e.g. Tabasco), 1 cup olive oil','Pulse the garlic and onion in a blender until very finely chopped.  Pour in orange juice, lime juice season with cumin, oregano, lemon-pepper, black pepper, salt, cilantro, and hot pepper sauce.  Blend until thoroughly incorporated.  Pour in the olive oil, and blend until smooth.\r\n','easy',1),
(6,'Cuban Mojito\r\n','10','2 servings\r\n','2 teaspoons white sugar, 1 lime cut into 4 wedges, 4 sprigs fresh mint, 1/2 cup white rum, 2 cups club soda, 2 cups crushed ice, 2 wedges lime as garnish','Place 1 teaspoon of sugar into each of two 12 ounce glasses. Squeeze the juice from a lime wedge into each glass, drop in the wedge, and add 2 sprigs of mint. Use a spoon or muddler to mash the sugar, lime juice, and mint together in the bottom of the glasses. Fill each glass about half full with crushed ice. Pour 1/4 cup rum into each glass. Fill the glasses with club soda, stir, and garnish with additional lime wedges.\r\n','easy\r\n',0),
(7,'Sofrito\r\n','20','5 cups','2 green bell peppers seeded and chopped, 1 red bell peppers seeded and chopped, 10 ajies dulces peppers tops removed, 3 medium tomatoes chopped, 4 onions cut into large chunks, 3 medium heads garlic peeled, 25 cilantro stems (with leaves), 25 recao stems (with leaves), 1 tablespoon salt, 1 tablespoon black pepper\r\n','In a food processor, combine green peppers, red peppers ajies dulces, tomatoes, onions, and garlic. Add cilantro, recao, salt, and pepper. Process to the consistency of semi-chunky salsa (not watery). Place in a resealable plastic freezer bag, and use as needed, or freeze in portions.\r\n','easy\r\n',0),
(8,'Fresh Banana Daiquiri\r\n','5','1 cocktail\r\n','1/2 large banana sliced, 1 1/2 fluid ounces light rum, 1 fluid ounce fresh lime juice, 1/2 fluid ounce triple sec, 1 teaspoon white sugar or to taste, 1 cup ice cubes','Combine banana, light rum, lime juice, triple sec, and sugar in a blende puree until smooth. Add ice cubes and blend on highest setting until slushy, 15 to 20 seconds. Pour into a glass and serve.','easy\r\n',0),
(9,'Jerk Chicken Wings\r\n','550','6 servings\r\n','1/2 yellow onion chopped, 1/2 cup green onions sliced, 6 cloves garlic, 3 habanero peppers seeded and chopped, 2 tablespoons fresh thyme leaves, 1 tablespoon kosher salt, 2 teaspoons ground black pepper, 2 teaspoons ground allspice, 1 teaspoon dried thyme, 1/2 teaspoon ground cinnamon, 1/2 teaspoon ground cumin, 1/2 teaspoon freshly grated nutmeg, 2 tablespoons vegetable oil, 3 tablespoons soy sauce, 2 tablespoons brown sugar, 1 cup lime juice, 3 pounds chicken wing drumettes, cooking spray','Put yellow onion, green onions, garlic, habanero peppers, fresh thyme, kosher salt, black pepper, allspice, dried thyme, cinnamon, cumin, nutmeg, vegetable oil, soy sauce, brown sugar, and lime juice, respectively, in a blender and blend until marinade is completely smooth.Place chicken in a large bowl. Pour marinade over chicken and toss to coat completely. Cover the bowl with plastic wrap and marinate in the refrigerator for at least 8 hours or overnight. Preheat oven to 450 degrees F (230 degrees C). Line a baking sheet with aluminum foil and spray with cooking spray. Place chicken drumettes on prepared baking sheet and reserve marinade left in the bowl. Bake in the preheated oven for 25 minutes. Brush 1/2 the reserved marinade onto chicken and turn wings over. Bake for 15 minutes. Turn chicken and brush on remaining 1/2 the reserved marinade. Bake until tender and caramelized, 10 to 15 minutes more. An instant-read thermometer inserted near the bone should read 165 degrees F (74 degrees C). Rest wings on baking sheet for 5 minutes before removing to a serving platter.','hard',0),
(10,'Mahi Mahi with Coconut Rice and Mango Salsa','120','4 servings\r\n','2 tablespoons olive oil, 1 1/2 teaspoons soy sauce, 2 teaspoons lemon juice, 1 clove garlic crushed, 2 teaspoons red pepper flakes, 1 teaspoon fresh ground black pepper, 1/2 teaspoon minced fresh ginger root, 2 tablespoons chopped green onion, salt to taste, 4 (4 ounce) mahi mahi fillets, 2 cups uncooked jasmine rice, 2 cups water, 1 cube chicken bouillon, 1 tablespoon butter, 3/4 (14 ounce) can coconut milk, 2 tablespoons white sugar, 1 1/2 teaspoons butter, 1 1/2 tablespoons white sugar, 1 1/2 cups fresh mango cubed','Whisk together the olive oil, soy sauce, lemon juice, garlic, red pepper flakes, black pepper, ginger, green onion, and salt in a bowl. Add the mahi mahi and toss to evenly coat. Cover the bowl with plastic wrap, and marinate in the refrigerator for 1 hour. Preheat the oven\'s broiler and set the oven rack in the middle of the oven. Bring the rice, water, chicken bouillon, and 1 tablespoon butter to a boil in a saucepan over high heat. Reduce heat to medium-low, cover, and simmer until the liquid has been absorbed, about 20 minutes. Pour in the coconut milk and 2 tablespoons of sugar. Stir, and simmer uncovered until the rice has absorbed most of the coconut milk. While the rice is cooking, remove the mahi mahi from the marinade, and shake off excess. Discard the remaining marinade. Place fish in a large baking dish in a single layer. Broil in the preheated oven until the fish flakes easily with a fork, 10 to 15 minutes. If the fish browns too quickly, cover the baking dish with a sheet of aluminum foil. Melt 1 1/2 teaspoons butter and 1 1/2 tablespoons of sugar in a skillet over medium-high heat. When the mixture begins to bubble, stir in mango cubes. Cook and stir until mango is tender, about 5 minutes. Serve by placing a mahi mahi fillet over a scoop of hot rice and top with the mango salsa.','medium',0),
(11,'Cuban-Style Yuca\r\n','30','6 servings\r\n','2 pounds yuca peeled and sliced lengthwise, 1/2 teaspoon salt, 1/4 cup olive oil, 1/2 onion diced, 4 cloves garlic minced, 1/2 teaspoon fresh lemon juice','Place the yuca into a pan and fill with enough water to cover. Stir in salt. Bring to a boil over medium-high heat, cover, and cook until tender, about 15 minutes. Drain, and place yucca on a serving plate. Meanwhile, place the olive oil, onion, garlic, and lemon juice into a pan. Cook over medium heat about 5 minutes. Pour the hot olive oil mixture over the yuca, and serve immediately.\r\n','easy',0),
(12,'Puerto Rican Steamed Rice\r\n','35','8 servings\r\n','2 tablespoons vegetable oil, 3 cups water, 1 teaspoon salt, 2 cups uncooked calrose rice rinsed','Bring vegetable oil, water, and salt to a boil in a saucepan over high heat. Add rice, and cook until the water has just about cooked out stir. Reduce heat to medium-low. Cover, and cook for 20 to 25 minutes. Stir again, and serve. Rice may be a little sticky and may stick to bottom of pot.\r\n','easy',0),
(13,'Chef John\'s Cuban Bread\r\n','735','2 loaves\r\n','1/2 teaspoon active dry yeast, 1/2 cup warm water, 1/2 cup flour, 1 package active dry yeast, 2 teaspoons white sugar, 3/4 cup warm water, 3 tablespoons lard, 2 teaspoons fine salt, 3 cups all-purpose flour or as needed divided, 1 tablespoon cornmeal, Water to spray tops of loaves','Combine 1/2 cup warm water, 1/2 teaspoon yeast, and 1/2 cup flour in a bowl or measuring cup. Whisk the starter until well blended. Cover with plastic wrap and refrigerate overnight. Place 1 package active dry yeast and 2 teaspoons sugar in a mixing bowl. Pour in 3/4 cup warm water. Let rest 15 minutes to ensure yeast is alive (bubbles will form on surface). Add lard and salt to bowl, add 1 cup of the flour. Mix until all ingredients are incorporated and dough forms a sticky ball. Add the starter (reserving 1/4 cup if you want to keep the starter going, if desired. Otherwise add it all). Sprinkle most of the rest of the flour on the dough, reserving 1/2 cup to be used if needed when kneading. Turn dough out onto a lightly floured work surface and knead until dough comes together in a firm ball, adding additional flour only as needed. Dough should be soft and supple with just a bit of tackiness on the surface. Place dough in a bowl and coat surface with a little vegetable oil. Cover bowl with a damp kitchen towel and place in a warm spot to rise. Let rise until at least doubled in size, about 2 hours. Line two rimmed baking sheets with parchment paper and sprinkle with a little cornmeal. Transfer dough onto lightly floured surface. Lightly press the dough into a rectangle with your lightly floured hands. Divide dough in half and press and shape each half into a long 1/2-inch thick rectangle about 12 inches long. Roll up tightly starting at the long end to form a skinny loaf. Flatten a bit. Transfer each loaf to a prepared baking sheet and dust with a bit of flour. Cover with a light, dry towel and let rise until doubled in size, 1 1/2 to 2 hours. Preheat oven to 400 degrees F (200 degrees C). Cut a 1/4-inch deep slit down the top of the loaves with a sharp knife or razor. Mist loaves lightly with water. Place pans in pre-heated oven, one pan on lower rack, one on higher rack. After 10 minutes, switch pan positions. Continue to bake until loaves are golden brown, 10 to 15 minutes longer. Transfer loaves to cooling rack and let cool to room temperature before slicing.','hard',0),
(14,'Tembleque Puerto Rican Coconut Pudding\r\n','195','6 4-ounce servings','2 (14 ounce) cans coconut milk, 3/4 cup sugar, 1/4 teaspoon kosher salt, 1/2 cup cornstarch, 1 pinch ground cinnamon','Stir coconut milk, sugar, and salt together in a saucepan. Spoon a few tablespoons of the coconut milk mixture into a small bowl and stir cornstarch into the mixture to dissolve, pour into the mixture in the saucepan. Bring the mixture to a boil while stirring constantly, cook until smooth and thick, about 5 minutes. Pour the coconut milk mixture into molds, cover each with plastic wrap, and refrigerate until cold and firm, 3 hours to 2 days. Run a thin knife around the edges of the mold and invert onto a plate to remove putting. Garnish tops with cinnamon.\r\n','hard',0),
(15,'Jamaican Jerked Chicken\r\n','510','4 servings\r\n','1/2 green onion, minced, 1/4 cup orange juice, 1 tablespoon minced fresh ginger root, 1 tablespoon minced jalapeno peppers, 1 tablespoon lime juice, 1 tablespoon soy sauce, 1 clove garlic minced, 1 teaspoon ground allspice, 1/4 teaspoon ground cinnamon, 1/2 teaspoon ground cloves, 1 1/2 pounds boneless skinless chicken thighs','Combine green onion, orange juice, ginger, jalapeno, lime juice, soy sauce, garlic, allspice, cinnamon, and cloves in resealable container. Seal and shake to combine. Add chicken and coat, marinate for 8 hours. Preheat an outdoor grill for medium heat and lightly oil the grate. Remove chicken, reserve marinade. Cook chicken on the preheated grill until no longer pink in the center and juices run clear, turning halfway through, 12 to 15 minutes. An instant-read thermometer inserted into the center should read at least 170 degrees F (77 degrees C). Meanwhile, bring reserved marinade to a boil in a small saucepan. Reduce heat, simmer, uncovered, until slightly thickened, about 5 minutes. Drizzle over cooked chicken.\r\n','hard',0),
(16,'Budin (Puerto Rican Bread Pudding)\r\n','300','1 budin\r\n','1 cup water, 2 (3 inch) cinnamon sticks, 15 whole cloves, 1 teaspoon anise seed, 2 tablespoons water, 1/2 cup white sugar, 1 (1 pound) loaf day-old bread, 4 cups evaporated milk, 4 eggs, 1 1/2 cups white sugar, 1 teaspoon vanilla extract, 3/4 teaspoon salt, 1/4 cup butter melted','Bring 1 cup of water to a boil in a small saucepan over high heat. Add the cinnamon sticks, cloves, and anise seeds. Cover, and set aside to steep for 15 minutes. Meanwhile, combine 2 tablespoons water with 1/2 cup sugar in a saucepan over medium-high heat. Stir occasionally to dissolve the sugar completely, but stop stirring once the mixture comes to a boil. Stay near the stove to monitor the color, swirling the pan gently to redistribute the caramel as the sugar begins to darken. Cook to about 310 degrees F (160 degrees C), or until the sugar turns light golden brown, then pour into a 9x5 inch loaf pan. Set aside to allow the caramel to harden. Preheat an oven to 350 degrees F (175 degrees C). Remove the crusts from the day-old bread, tear the bread into cubes, and place into a large mixing bowl. Strain the spice tea through a fine mesh sieve to remove the spices. Add to the bread along with the evaporated milk. Stir to evenly moisten, and set aside for 10 minutes. Whisk the eggs in a large mixing bowl along with 1 1/2 cups of sugar, the vanilla extract, salt, and melted butter. Stir in the moistened bread mixture until evenly mixed. Pour into the loaf pan over the caramel. Line a roasting pan with a damp kitchen towel.  Place the loaf pan on the towel, inside roasting pan, and place roasting pan on oven rack. Fill roasting pan with boiling water to reach halfway up the sides of the loaf pan. Bake in the preheated oven until a toothpick inserted into the center comes out clean, about 1 hour and 15 minutes. Cool in the pan for about an hour, then refrigerate until cold, 2 hours more. When ready, invert the budin onto a serving plate. The caramel will have turned to a syrup and will cover the budin like a sauce.','hard',0),
(17,'Mojito Perfecto\r\n','5','2 cocktails\r\n','6 mint leaves, 4 teaspoons white sugar, 1 lime, cut into 6 wedges, 2 (1.5 fluid ounce) jiggers lemon-flavored rum, 1 cup ice cubes or as needed, 1/2 cup carbonated water or as needed','Put 3 mint leaves and 2 teaspoons sugar into each of 2 glass tumblers, vigorously stir sugar and mint together, crushing mint with the back of a spoon to release oils. Add 3 lime wedges to each glass, again stir vigorously to release some lime juice. Pour 1 jigger rum into each glass. Fill glasses with ice cubes and top with carbonated water stir.\r\n','easy',0),
(18,'Caribbean Fish Soup\r\n','125','8 servings\r\n','2 whole fish, scaled and cleaned or more to taste, 1 lemon juiced, 8 cups water, 4 green bananas chopped, 1 pound pumpkin cut into 1-inch pieces or more to taste, 2 potatoes chopped, 2 ears corn cut into 1-inch pieces, 4 ounces carrots cut into 1/2-inch pieces, 1/2 cup chopped okra, 4 scallions chopped, 1 hot chile pepper, 2 cloves garlic chopped, 1 teaspoon salt, 1 teaspoon ground black pepper, 4 sprigs fresh thyme leaves stripped','Rinse fish with lemon juice drain. Bring water to a boil in a large bowl. Add fish, simmer until soft, about 30 minutes. Strain fish, reserving broth. Let fish cool. Remove bones, trying to keep large pieces of fish intact. Bring broth to a boil. Add green bananas, pumpkin, potatoes, corn, carrots, okra, scallions, chile pepper, garlic, salt, pepper, and thyme. Bring back to a boil. Reduce heat to low, simmer until potatoes are almost tender, about 10 minutes. Stir in fish. Simmer until flavors combine, about 5 minutes more. Remove soup from heat and let stand before serving, about 30 minutes. Discard chile pepper.\r\n','hard',0),
(19,'Dark n Stormy Cocktail\r\n','5','1 cocktail\r\n','2 fluid ounces dark rum, 4 fluid ounces ginger beer, 1/2 cup ice','Combine rum and ginger beer in an old-fashioned glass. Add ice and stir.\r\n','easy',0),
(20,'Jamaican Cabbage\r\n','40','6 servings','1 head cabbage, 2 tablespoons olive oil or as needed, 1 small onion thinly sliced, 1/2 chopped green bell pepper, 1 green onion sliced, 2 sprigs fresh thyme, 1 whole Scotch bonnet chile pepper, 1 teaspoon salt, 1 cup shredded carrots, 1/4 cup white vinegar, 2 tablespoons white sugar','Peel tough outer leaves from cabbage, core the head, and shred cabbage. Heat olive oil in a large skillet over medium high heat. Raise heat to high. Stir onion, green bell pepper, and green onion in the hot oil and cook until vegetables have softened, about 5 minutes, stirring often. Stir thyme, Scotch bonnet pepper, and salt into onion mixture. Mix shredded cabbage and carrots into onion mixture until thoroughly combined, cover skillet, and reduce heat to medium-low. Cook until cabbage has started to soften, about 10 minutes, stirring occasionally. Uncover skillet and stir vinegar and sugar into cabbage mixture, cook and stir until cabbage is tender, about 3 more minutes. Discard Scotch bonnet pepper and thyme sprigs before serving.\r\n','medium',0),
(21,'Cuban-Style Yellow Rice\r\n','30','12 cups\r\n','4 cups long grain rice, 8 cups water, 1 small onion minced, 2 teaspoons salt, 1 teaspoon annatto powder, 1 teaspoon paprika, black pepper to taste, 1 cup frozen peas thawed, 1 (4 ounce) jar sliced pimento peppers for garnish','Place the rice in a sieve and rinse under cold water until the water runs clear. Shake sieve to remove excess water from rice. Place rice in a large saucepan with a tightly fitting lid and add water. Stir in the onion, salt, annatto powder, paprika, and pepper. Bring the mixture to a boil over medium-high heat. Reduce heat to low, cover pan, and simmer. After cooking for 10 minutes, gently stir the peas into the rice. Cook until all the water is evaporated and the rice is tender, 15 to 20 minutes longer. Serve garnished with pimento slices.\r\n','medium',0),
(22,'Jerk Seasoning\r\n','10','1/4 cup\r\n','2 tablespoons dried minced onion, 2 1/2 teaspoons dried thyme, 2 teaspoons ground allspice, 2 teaspoons ground black pepper, 1/2 teaspoon ground cinnamon, 1/2 teaspoon cayenne pepper, 1/2 teaspoon salt, 2 tablespoons vegetable oil','In a small bowl, stir together the dried onion, thyme, allspice, ground black pepper, cinnamon, cayenne pepper, and salt. Coat meat lightly with oil, then rub seasoning onto meat.\r\n','medium',0),
(23,'Dark \'n\' Stormy Cocktail\r\n','5','1 cocktail\r\n','2 fluid ounces dark rum, 4 fluid ounces ginger beer, 1/2 cup ice','Combine rum and ginger beer in an old-fashioned glass. Add ice and stir.\r\n','easy',0),
(24,'Puerto Rican Breakfast Custard','30','2 servings\r\n','2 tablespoons cornstarch, 1 teaspoon salt, 3 tablespoons white sugar, 1 teaspoon ground cinnamon, 2 cups whole milk','Whisk together the cornstarch, salt, sugar, and cinnamon in a large saucepan. Stir in the milk to evenly blend ingredients, and set over medium-high heat. Continue whisking and cooking until custard reaches a thick consistency, 25 to 30 minutes. It is important to stir the entire time, or the custard can easily burn or clump. The custard will continue to thicken as it cools. Spoon into bowls to serve.\r\n','medium',0),
(25,'Pastelon de Platano Maduro (Dominican-Style Yellow Plantain Pie)\r\n','55','6 servings\r\n','cooking spray, 10 plantains peeled and broken into chunks, 1/2 teaspoon salt, 1/2 cup milk, 1/4 cup butter, 1 tablespoon canola oil, 1 pound ground beef, 1 yellow onion chopped, 1 green bell pepper chopped, 1/2 cup tomato sauce, 1 teaspoon crushed garlic, 1/2 cube chicken bouillon, 1/2 pound shredded Cheddar cheese','Preheat oven to 400 degrees F (200 degrees C). Spray a baking dish with cooking spray. Place plantains and salt into a large pot and cover with water, bring to a boil. Reduce heat to medium-low and simmer until plantains turn a darker yellow, add 1 cup water to the pot, bring to a boil, and cook until tender, about 15 minutes. Drain. Mash plantains, milk, and butter together in the pot until smooth. Heat oil in a large skillet over medium heat. Cook and stir ground beef, onion, bell pepper, tomato sauce, garlic, and chicken bouillon, adding water if mixture gets too dry, in hot oil until beef is browned and cooked through, 10 to 12 minutes. Spread 1/2 of the mashed plantains into the bottom of the prepared baking dish. Pour meat mixture over the plantains and top with Cheddar cheese. Spread remaining mashed plantains over the cheese. Bake in the preheated oven until plantains are golden and filling is bubbling, about 10 minutes.\r\n','medium',0),
(26,'Mofongo\r\n','30','2 servings\r\n','3 cups canola oil for frying, 3 cloves garlic or to taste, 3 tablespoons olive oil, 1 cup crushed fried pork skins, 2 green plantains peeled and sliced into 1/2 inch rounds, salt to taste','Heat canola oil in a deep-fryer or large saucepan to 350 degrees F (175 degrees C). Mash the garlic with the olive oil in a mortar and pestle. Combine garlic mixture with the pork rinds in a large bowl, set aside. Fry the plantain chunks until golden and crispy, but not brown, about 15 minutes. Transfer the fried plantains into the bowl with the garlic mixture. Toss to coat. Mash the coated plantains with the mortar and pestle until smooth. Season with salt. Roll the plantain mixture into two large balls or several small balls before serving.\r\n','medium',0),
(27,'Quick and Easy Black Beans and Rice','40','6 servings\r\n','2 tablespoons olive oil, 1 small onion chopped, 3 cloves garlic minced, 2 cups water, 1 (15.5 ounce) can black beans, 1 teaspoon ground cumin, 1 beef bouillon cube, 1 cup rice, 1/2 teaspoon Creole seasoning or to taste, 1/2 teaspoon dried cilantro','Heat olive oil in a saucepan over medium heat. Cook and stir onion and garlic in hot oil until softened, 5 to 7 minutes. Stir water, black beans, cumin, and beef bouillon cube into the onion and garlic mixture, bring to a boil, add rice, cover, and simmer until the rice is tender and the moisture is absorbed, about 20 minutes. Gently stir Creole seasoning and cilantro into the beans and rice.\r\n','medium',0),
(28,'Mangu\r\n','40','6 servings\r\n','3 green plantains, 1 quart water, 1/4 cup olive oil, 1 cup sliced white onion, 1 1/2 tablespoons salt, 1 cup sliced Anaheim peppers','Place the plantains and water in a saucepan. Bring to a boil, and cook 20 minutes, until plantains are tender but slightly firm. Drain, reserving 1 cup of the liquid. Cool plantains, and peel. Heat the olive oil in a skillet over medium heat, and saute the onion until tender. In a bowl, mash the plantains with the reserved liquid and salt. Transfer to a food processor, mix in the peppers, and puree. Serve the pureed plantain mixture topped with the onions.\r\n','medium',0),
(29,'Limber de Coco (Coconut Ice)','485','4 servings\r\n','1/2 (14 ounce) can coconut milk, 1/2 (12 fluid ounce) can evaporated milk, 1/4 cup white sugar, 1 teaspoon vanilla extract, 1/2 teaspoon ground cinnamon','Mix coconut milk, evaporated milk, sugar, vanilla extract, and cinnamon together in a bowl or blender until sugar dissolves and mixture is thoroughly combined. Pour mixture into ice trays or popsicle molds. Freeze 8 hours to overnight.','hard',1),
(30,'Horchata de Arroz (Rice Drink)\r\n','735','1 quart\r\n','1 cup uncooked long grain white rice, 3 ½ cups cold water, 1 (12 fluid ounce) can evaporated milk, ½ cup white sugar, ½ teaspoon ground cinnamon, 1 teaspoon vanilla extract\r\n','Combine tequila, mint leaves, sugar, and lime wedges in a tall glass vigorously stir the mixture, crushing mint with the back of a spoon to release oils and squeezing juice from the lemon wedges. Top with club soda and stir gently to serve.\r\n','hard',0),
(31,'Mango Pudding (Flan de Mango)\r\n','60','12 servings\r\n','1 cup white sugar, 1 tablespoon lemon juice, 2 cups pureed mango, 1 (14 ounce) can sweetened condensed milk, 2 tablespoons cornstarch, 1 tablespoon rum, 1 cup evaporated milk, 6 eggs beaten, 1 pinch salt','Preheat oven to 350 degrees F (175 degrees C). Fill a large, shallow baking pan with about 1 1/2 inches water. In an 8x13 inch aluminum baking pan over medium heat, mix the sugar and lemon juice. Cook and stir until caramelized. Remove from heat, and blend in mango, sweetened condensed milk, cornstarch, rum, evaporated milk, eggs, and salt. Set pan with the mango mixture into the pan with water. Place in the preheated oven, and bake 45 minutes, or until firm. Cool before turning out onto a platter.\r\n','medium',0),
(32,'Trinidad\'s Ponche-de-Creme (Punch with Cream)\r\n','15','6 servings\r\n','6 eggs beaten, 2 teaspoons grated lime zest, 3 (14 ounce) cans, sweetened condensed milk, 3/4 cup canned evaporated milk, 1 1/2 cups rum, 1 tablespoon aromatic bitters, 1 pinch freshly grated nutmeg','In a large bowl, beat eggs and lime zest using an electric mixer until light and fluffy. Gradually pour in the condensed milk while continuing to mix, and then pour in the evaporated milk. Stir in the rum and bitters, and sprinkle with nutmeg. Transfer to a bottle and chill for at least 1 hour before serving. Serve over crushed ice.\r\n','easy',0),
(33,'Coconut-Lime Cheesecake with Mango Coulis\r\n','570','1 9-inch cheesecake\r','3/4 cup sweetened flaked coconut, 3/4 cup crushed gingersnap cookies, 3 tablespoons melted butter, 2 (8 ounce) packages cream cheese softened, 1 (10 ounce) can sweetened condensed milk, 2 eggs, 1 tablespoon lime zest, 2 tablespoons lime juice, 1 tablespoon coconut extract, 2 cups cubed fresh mango, 1 teaspoon white sugar or more to taste','Preheat oven to 325 degrees F (165 degrees C). Lightly grease a 9-inch springform pan. Combine the coconut, gingersnap cookies, and melted butter in a bowl, mix until evenly moistened. Press the cookie mixture into the bottom and slightly up the sides of the prepared pan. Bake the crust in the preheated oven until browned and set, about 10 minutes. Set aside to cool. Reduce oven heat to 300 degrees F (150 degrees C). Beat the softened cream cheese in mixer bowl until smooth. With beater set to medium-low, slowly pour the condensed milk into the bowl, mixing only until just blended, stopping to scrape the sides of the bowl as necessary. Add the eggs, individually, allowing the first to blend into the mixture before adding the second, again, scrape the sides of the bowl as necessary. Pour about half of the cream cheese batter into a separate bowl. Stir the lime juice and lime zest into the portion in the new bowl, pour the batter over the crust in the springform pan, smoothing into an even layer.Stir the coconut extract through the remaining cream cheese batter, pour over the lime-flavored batter in the springfom pan, smoothing into an even layer. Bake in the preheated oven until the top of the cheesecake springs back when gently pressed, about 45 minutes. Turn oven heat off, but leave cheesecake inside with oven door slightly ajar until the oven cools completely. Refrigerate until completely chilled. Prepare mango coulis by pureeing the mango with sugar until smooth. If too thick, add a teaspoon of water at a time, using just enough to make pourable. Drizzle over cheesecake when plated.','hard',1),
(34,'We Be Jammin\' Jamaican Banana Bread\r\n','165','2 loaves\r\n','2 tablespoons unsalted butter softened, 2 tablespoons cream cheese, 1 cup white sugar, 1 egg, 2 cups all-purpose flour, 2 teaspoons baking powder, 1/2 teaspoon baking soda, 1 teaspoon salt, 1 cup mashed overripe bananas, 1/2 cup milk, 2 tablespoons dark rum or rum flavoring, 1/2 teaspoon lime zest, 2 teaspoons lime juice, 1 teaspoon vanilla extract, 1/4 cup chopped toasted pecans, 1/4 cup flaked coconut, 1/4 cup brown sugar, 2 teaspoons unsalted butter, 2 teaspoons dark rum or rum flavoring, 2 tablespoons chopped toasted pecans, 2 tablespoons flaked coconut','Preheat oven to 375  degrees F (190 degrees C). Lightly grease two 8x4 inch loaf pans. Beat together 2 tablespoons of softened butter and cream cheese in a large bowl until fluffy. Slowly beat in sugar until well incorporated. Add the egg and mix well. Sift together the flour, baking powder, baking soda, and salt in a separate bowl. In a different bowl, mix together the bananas, milk, 2 tablespoons rum, lime zest, lime juice, and vanilla extract, stir well. Pour 1/3 of the flour mixture into the butter and mix well. Mix in 1/2 of the mashed bananas. Continue with another 1/3 of the flour, followed by the remaining banana mixture, and finally the remaining flour. Fold in 1/4 cup pecans and 1/4 cup coconut flakes. Pour the mixture into the loaf pans, and bake in the preheated oven until a toothpick inserted into the center comes out clean, about one hour. When finished, cool for 10 minutes in the pan, remove, and finish cooling on a wire rack. After you take the banana bread out of the oven, prepare the topping by stirring together the brown sugar, remaining butter, lime juice, and 2 teaspoons of rum in a small saucepan over medium-high heat. Bring to a simmer stirring constantly, cook until the sugar has dissolved and the mixture is smooth, about one minute. Remove from heat, and stir in 2 tablespoons pecans, and 2 tablespoons coconut. Spoon this topping over the loaves while they are still warm. The topping will harden slightly when the loaf cools.','hard',0),
(35,'Chef John\'s Hummingbird Cake\r\n','200','1 9-inch layer cake\r','2 cups white sugar, 3 cups all-purpose flour, 1 teaspoon ground cinnamon, 1 teaspoon baking soda, 1 1/4 teaspoons kosher salt, 1 1/2 cups vegetable oil, 3 large eggs beaten, 1 1/2 teaspoons vanilla extract, 1 cup crushed pineapple, 3 medium ripe bananas sliced, 1 cup chopped pecans toasted, 2 (8 ounce) packages cream cheese, softened, 1/2 cup unsalted butter at room temperature, 1 teaspoon vanilla extract, 1 (16 ounce) package powdered sugar, 1/2 cup white sugar or as needed, 1/4 cup edible flowers assorted','Preheat the oven to 350 degrees F (175 degrees C). Butter two 9-inch round cake pans, then dust with flour. Set aside. Combine sugar, flour, cinnamon, baking soda, and salt in a large mixing bowl, whisk quickly to combine. Add oil and eggs and mix with a spatula until just combined. Add vanilla, pineapple, bananas, and toasted pecans, and mix until thoroughly combined. Divide batter evenly between the prepared pans. Shake each pan then tap on the counter to settle the batter and bring any air bubbles to the top. Bake in the preheated oven until a wooden skewer inserted in center comes out clean, about 35 minutes. Let cakes cool in pan for 10 minutes before removing to a wire rack. Let cool completely, at least 1 hour. Combine cream cheese, butter, and vanilla in the bowl of a stand mixer. Using the whisk attachment on high speed, mix until smooth and creamy, scraping down the sides as necessary with a spatula. Mix in the powdered sugar on a lower speed in 3 or 4 additions until mostly incorporated. Increase to high speed and whip until light and fluffy. Place one cake on a serving platter. Spread 1/2 of the frosting on top, leaving 1/4  to 1/2 inch unfrosted at the edges. Top with second cake layer and give it a firm but gentle press. Pile remaining frosting on top and spread toward the outside. Place in the refrigerator to chill for 1 hour. Meanwhile, draw or trace a hummingbird template on a piece of paper and lay on a baking sheet under a silicone mat (such as Silpat&reg). Heat sugar for hummingbird in a saucepan over medium-low heat until dissolved, hot, and amber in color. Drip liquid sugar onto the silicon mat, tracing the hummingbird pattern. Let sit until hard. Place cooled hummingbird on top of cake and decorate with edible flowers.','hard',0),
(36,'Caribbean Slaw','80','8 servings\r\n','1/2 head green cabbage shredded, 1 red bell pepper thinly sliced, 1/2 red onion thinly sliced, 2 carrots peeled and shredded, 1 mango - peeled seeded and diced, 1/2 cup fresh cilantro chopped, 1 cup nonfat plain yogurt, 2 tablespoons reduced-fat mayonnaise, 1 tablespoon prepared yellow mustard, 1 tablespoon apple cider vinegar, 1 teaspoon agave nectar, salt and black pepper to taste, 1 dash habanero hot sauce or more to taste','Toss the cabbage, red bell pepper, red onion, carrots, mango, and cilantro together in a large bowl. Whisk the yogurt, mayonnaise, mustard, cider vinegar, agave nectar, salt, pepper, and hot sauce together in a small bowl, pour over the cabbage mixture and toss to coat. Allow the slaw to marinate in the refrigerator for at least 1 hour to allow the flavors to combine.\r\n','medium',0),
(37,'Warm Korean Salad','25','4 servings','250 g soba noodles or 250 g thin spaghetti, 2 teaspoons sesame oil, 1 cup broccoli floret, 1 medium red capsicum thinly sliced, 12 red onions cut into thin wedges, Sauce, 1 1/2 tablespoons smooth peanut butter, 1/4 cup warm water, 2 tablespoons soy sauce, 1 1/2 tablespoons mirin, 2 garlic cloves crushed, 1 teaspoon finely chopped gingerroot, 2 teaspoons sweet Thai sweet chili sauce, 1/4 cup thinly diagonally sliced green onion, 4 teaspoons sesame seeds toasted','Cook the noodles according to the packet directions, drain, transfer to a large bowl and toss well with the sesame oil. Heat a frying pan and spray with oil. Add the capsicum, broccoli and onion and stir fry for about 3 minutes-or until tender-crisp. In a medium bowl, blend the peanut butter and warm water. Add the soy sauce, mirin, vegetables to the noodles, spoon sauce over and toss. Add the garlic ginger, chili sauce and spring onions, whisk well. Sprinkle with the sesame seeds and serve.','easy',1),
(38,'Vegan Mofongo (Fried Mashed Plantains)\r\n','45','4 servings\r\n','5 large green plantains coarsely chopped, 1 can organic tomato sauce, 1 small bunch cilantro chopped or to taste, 2 tablespoons homemade sofrito, 2 tablespoons olive oil or to taste divided, 1 clove garlic minced, 1 packet sazon seasoning, 1/2 cup vegetable broth or to taste, salt and ground black pepper to taste','Fill a 1-quart pot with water, boil plantains with a pinch of salt until easily pierced with a fork, about 25 minutes. Mash plantains with tomato sauce, cilantro, sofrito, 1 tablespoon olive oil, garlic, and sazon in a mortar or glass bowl. Incorporate the remaining 1 tablespoon olive oil and enough vegetable broth to ensure that mofongo sticks together but is dry enough to easily slip out of a container. Season with salt and pepper. Serve mofongo on top of the remaining 5 tablespoons vegetable broth in a bowl.\r\n','easy',0),
(39,'Cuban Inspired Millet\r\n','55','8 servings\r\n','1 carrot, chopped, 2 cloves garlic crushed, 1 tablespoon olive oil, 1 onion chopped, 1 green bell pepper chopped, 1 cup millet, 2 cups vegetable broth, salt and ground black pepper to taste, 1/4 cup chopped fresh cilantro or more to taste','Blend carrot and garlic in a food processor until finely chopped. Heat olive oil in a pot over medium heat, cook and stir carrot mixture, onion, and green bell pepper until softened, about 10 minutes. Add millet, stir until fragrant and toasted, about 3 minutes. Pour vegetable broth into millet mixture, season with salt and black pepper. Reduce heat and simmer until all the broth is absorbed and millet is tender, about 20 minutes. Stir in cilantro.\r\n','medium',0),
(40,'Surullitos de Maiz (Cornmeal Sticks)\r\n','35','50 sticks\r\n','2 cups water, 1 1/4 teaspoons salt, 1 1/2 cups yellow cornmeal, 5 tablespoons white sugar or to taste, 4 ounces Edam cheese shredded, 2 cups oil for deep frying, 1 cup ketchup, 1 cup mayonnaise','Combine the water and salt in a saucepan, and bring to a boil. Remove from the heat, and stir in the cornmeal and sugar. Return to medium heat, and cook stirring constantly until the mixture pulls away from the sides of the pan. Remove from heat, and stir in the Edam cheese until well blended. Roll tablespoonfuls of the cornmeal mixture into balls. Then roll the balls into small fat sticks about 3 inches long. In a medium bowl, mix together the ketchup and mayonnaise to make the dipping sauce. Set aside. Heat oil in a large heavy skillet to 375 degrees F (190 degrees C). Carefully place some of the corn sticks into the oil so they are not crowded. Fry until golden brown, 3 to 4 minutes. Remove from hot oil, and drain on paper towels. Serve immediately with the sauce.','medium',0),
(41,'Basil-Cucumber Mojito\r\n','10','1 mojito\r\n','3 slices 1/4 inch thick slices cucumber, 8 leaves basil or more to taste, 2 lime slices, 2 (1.5 fluid ounce) jiggers rum, 2 raw sugar cubes, ice cubes as desired, 1 splash club soda, 1 cucumber wedge for garnish, 1 sprig fresh basil for garnish','Put cucumbers, basil leaves, lime slices, rum, and raw sugar cubes into a metal cocktail shaker. Mash mixture together with a muddler until the sugar cubes have dissolved. Add ice, place lid onto the shaker, and shake vigorously, strain into a chilled glass tumbler filled with ice. Top cocktail with club soda and garnish with cucumber wedge and basil sprig.\r\n','easy',0),
(42,'Puerto Rican Garlic Marinade\r\n','5','8 servings\r\n','1/2 cup olive oil, 4 teaspoons crushed garlic, 1 tablespoon salt, 2 1/2 teaspoons black pepper','In a blender or food processor, combine olive oil, garlic, salt, and pepper. Process for 3 to 5 minutes.\r\n','easy',0),
(43,'The Real Mojito\r\n','10','1 cocktail','10 fresh mint leaves, 1/2 lime cut into 4 wedges, 2 tablespoons white sugar or to taste, 1 cup ice cubes, 1 1/2 fluid ounces white rum, 1/2 cup club soda','Place mint leaves and 1 lime wedge into a sturdy glass. Use a muddler to crush the mint and lime to release the mint oils and lime juice. Add 2 more lime wedges and the sugar, and muddle again to release the lime juice. Do not strain the mixture. Fill the glass almost to the top with ice. Pour the rum over the ice, and fill the glass with carbonated water. Stir, taste, and add more sugar if desired. Garnish with the remaining lime wedge.\r\n','easy',0),
(44,'Sazon\r\n','5','10 servings','1 tablespoon ground coriander, 1 tablespoon ground cumin, 1 tablespoon garlic powder, 1 tablespoon ground annatto seed, 1 1/2 teaspoons ground turmeric, 1 teaspoon ground black pepper, 1 tablespoon kosher salt, 1 1/2 teaspoons dried Mexican oregano','Combine coriander, cumin, garlic powder, annatto, turmeric, black pepper, salt, and Mexican oregano in an air-tight container and mix well.\r\n','easy',0),
(45,'Corn and Rice\r\n','70','5 servings\r\n','1 slice bacon chopped, 1/2 onion chopped, 1/4 green bell pepper chopped, 1/2 teaspoon chopped fresh thyme, 1/2 cup tomato sauce, 1 teaspoon browning sauce, 1 teaspoon salt, 1/2 teaspoon ground black pepper, 1 pinch red pepper flakes, 2 (14 ounce) cans whole kernel corn drained, 3 1/2 cups water, 2 cups white rice','Cook the bacon in a large saucepan over medium heat until the grease begins to render. Stir in the onion, bell pepper, and thyme, cook until the onion is nearly translucent. Reduce heat to medium-low and add the tomato sauce, browning sauce, salt, black pepper, and red pepper flakes, stir, simmer another 3 minutes. Add the corn, simmer another 3 minutes. Slowly pour the water into the mixture while stirring. Raise the heat to high and stir in the rice, bring to a boil, cover and reduce heat to low. Simmer until the rice has absorbed all the moisture, about 30 minutes, fluff with a fork to serve.\r\n','medium',0),
(46,'Caribbean Coconut Bread\r\n','90','1 loaf\r\n','1 teaspoon butter softened, 1 3/4 cups all-purpose flour, 1 1/2 cups white sugar, 1 cup shredded coconut, 1 teaspoon baking powder, 3/4 teaspoon salt, 2 eggs, 1 cup low-fat milk, 1/4 cup water, 1/4 cup canola oil, 1 1/4 teaspoons coconut extract, 1 teaspoon vanilla extract, 1/2 teaspoon ground cinnamon','Preheat oven to 350 degrees F (175 degrees C). Grease a loaf pan with butter. Combine flour, sugar, coconut, baking powder, and salt in a large bowl, stir once or twice with a wooden spoon. Add eggs, milk, water, oil, coconut extract, vanilla extract, and cinnamon. Mix well until batter is blended. Pour batter into the greased loaf pan. Bake in the preheated oven until a toothpick inserted into the center comes out clean, about 1 hour. Cool in the pan for 15 minutes. Invert onto a wire rack to cool completely.\r\n','medium',0),
(47,'Korean Baesuk Frozen Yogurt (For Ice Cream Maker)','35','8 servings\r\n','2 korean pears, 1/2 cup sugar, 16 ounces Greek yogurt, 1 teaspoon vanilla extract, 1-2 teaspoon ginger juice, 1 dash lemon juice','First begin by peeling two Korean pears (aka Asian pears) and chopping into small pieces. Place the pear pieces together with a dash of lemon juice into a blender with just enough water as was necessary to grind them to a smooth mixture. Combine 16 oz of Greek yogurt (rBGH free) together with the Korean pear mixture and 1/2 cup sugar in the ice cream maker. While the mixture is churning in an ice cream maker, add 1-2 tsp ginger juice. Also add 1/2 tsp vanilla extract. After 30 mins of churning, the frozen baesuk yogurt will be ready to freeze in a freezer. Place into a plastic container and allow to freeze for at least four hours before serving.','medium',0),
(48,'Hot Banana Salsa','30','24 cups\r\n','1 large firm banana peeled and diced, 1/2 cup red bell pepper seeded and diced, 1/2 cup green bell pepper seeded and diced, 1/2 cup yellow bell pepper seeded and diced, 3 tablespoons chopped fresh cilantro, 2 green onions chopped, 2 tablespoons fresh lime juice, 1 tablespoon brown sugar, 2 teaspoons minced fresh ginger root, 2 teaspoons olive oil, 1 teaspoon minced habanero pepper, salt to taste','Mix together the banana, red pepper, green pepper, yellow pepper, cilantro, green onion, lime juice, brown sugar, ginger, olive oil, and habanero pepper in a bowl, season with salt. Serve within 1 hour.\r\n','medium',1),
(49,'Coconut Conch Chowder\r\n','65','8 servings\r\n','1 pound conch meat, 1/4 cup margarine divided, 2 green onions chopped, 1 carrot diced, 1 stalk celery diced, 1 small sweet potato peeled and diced, 1 small red bell pepper diced, 1/2 cup fresh corn kernels, 2 tablespoons all-purpose flour, 1 quart half-and-half, 1 (14 ounce) can unsweetened coconut milk, 2 cups fish stock, 1 1/2 tablespoons grated fresh ginger root, salt and pepper to taste, 1 1/2 teaspoons hot sauce, 1 bunch fresh cilantro chopped','Place conch meat in a pot with enough water to cover, and bring to a boil. Cook 15 minutes. Drain, and finely chop in a food processor. Melt 2 tablespoons margarine in a skillet over medium heat, and mix in the green onions, carrot, celery, sweet potato, red pepper, and corn. Cook and stir 5 minutes. Melt remaining 2 tablespoons margarine in a large pot, and whisk in the flour to create a roux. Pour in the half and half, coconut milk, and fish stock. Mix in the ginger, and season with salt and pepper. Stir the conch and vegetables into the pot. Bring to a boil, reduce heat to low, and simmer 15 minutes. Mix in the hot sauce and cilantro. Continue cooking 15 minutes, or to desired consistency.\r\n','medium',0),
(50,'Authentic Bahamian Peas and Rice','55','8 servings','1 tablespoon vegetable oil, 1 onion chopped, 1/2 green bell pepper chopped, 8 ounces cubed cooked ham, 1 tablespoon tomato paste, 1 tomato chopped, 2 slices bacon cooked and crumbled, 8 ounces corned beef chopped, 1 (15 ounce) can pigeon peas drained, 2 sprigs fresh thyme, salt and pepper to taste, 1 (10 ounce) can coconut milk, 6 cups water, 1 teaspoon browning sauce, 3 cups uncooked brown rice','Heat oil in a large pot over medium heat. Add the onion, and fry until transparent. Stir in the green pepper, ham, tomato paste, tomato, bacon, corned beef, and pigeon peas. Season with thyme, salt, and pepper. Bring to a simmer. Stir in the coconut milk, water and browning sauce, and bring to a boil. Stir in the rice. Return to a boil, then stir, cover, and reduce the heat to low. Simmer for about 45 minutes, until rice is tender. Stir occasionally.\r\n','medium',0);

/*Table structure for table `user` */

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(50) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb4;

/*Data for the table `user` */

insert  into `user`(`id`,`username`,`password`) values 
(36,'ivana10','40f03b3eb82aea157048232f75d4745e2f5846f2d0185ce1fc4b523ef892952b'),
(39,'ivana','feee3235626c079da26ff0ccbacba430f809cdf5a8dc7358aee52f05ae2e6ed0'),
(41,'ivana13','985b271e6a163a1138fd18d237ad3b209fb4c892900ee3fb9ad22cdaac0221da'),
(43,'ivana101','1cea09a12c91d97356664281e89d20399dcd5dcf4b86e2587164a01487a04968'),
(48,'ivana37','48893c7238cad62233422369a8b2b4c160372128c717f268c946dd855c184e56');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
